Repository isaaceindhoven/testcafe-reporter-allure, pull requests merged in 2020-10, with the labels that each got.

#41 Copy screenshots to allure folder
  .gitignore
  src/reporter/allure-reporter.ts
  tests/unit/reporter/allure-reporter.spec.ts
Labels: enhancement

#43 fix: set historyId to uuid instead of test name
  package-lock.json
  package.json
  src/reporter/allure-reporter.ts
  tests/unit/reporter/allure-reporter.spec.ts
Labels: bug

#46 fix(reporter): fix default detailsMessage and detailsTrace value
  allure-categories.config.js
  package-lock.json
  package.json
  src/reporter/allure-reporter.ts
  src/utils/utils.ts
  tests/e2e/example.spec.ts
  tests/unit/reporter/allure-reporter-merger.spec.ts
  tests/unit/reporter/allure-reporter.spec.ts
Labels: bug, hacktoberfest-accepted
